[project]
name = "so-assistant-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.116.1",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.41",
    "uvicorn[standard]>=0.35.0",
]
