"""API schemas (request/response models)."""
from app.api.schemas.common import (
    BaseResponse,
    SuccessResponse,
    ErrorResponse,
    ValidationErrorResponse,
    PaginationMeta,
    PaginatedResponse,
    ListResponse,
    create_success_response,
    create_error_response,
    create_validation_error_response,
    create_list_response,
    create_paginated_response,
)
from app.api.schemas.projects import (
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectState,
)
from app.api.schemas.solution_outlines import (
    SolutionOutlineBase,
    SolutionOutlineCreate,
    SolutionOutlineUpdate,
    SolutionOutlineUpsert,
    SolutionOutlineResponse,
    SolutionOutlineVersionInfo,
    SolutionOutlineStatus,
)
from app.api.schemas.adrs import (
    ADRBase,
    ADRCreate,
    ADRUpdate,
    ADRResponse,
)
from app.api.schemas.review_comments import (
    ReviewCommentBase,
    ReviewCommentCreate,
    ReviewCommentUpdate,
    ReviewCommentResponse,
    ReviewCommentStatus,
)
from app.api.schemas.teams import (
    TeamBase,
    TeamCreate,
    TeamUpdate,
    TeamResponse,
)
from app.api.schemas.tasks import (
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskStatus,
)
from app.api.schemas.sse import (
    SSEMessageBase,
    SSEMessageCreate,
    SSEMessageResponse,
    SSEClientInfo,
    SSEClientsResponse,
    SSEClientDisconnectResponse,
    SSEClientsDisconnectResponse,
    SSEHeartbeatResponse,
)
from app.api.schemas.llm import (
    LLMRequestBase,
    LLMRequest,
    LLMStreamRequest,
    LLMResponseBase,
    LLMResponse,
    LLMStreamResponse,
    LLMErrorResponse,
)
from app.api.schemas.requirements import (
    RequirementBase,
    RequirementCreate,
    RequirementUpdate,
    RequirementResponse,
    RequirementCategory,
    RequirementStatus,
    RequirementDocumentBase,
    RequirementDocumentCreate,
    RequirementDocumentUpdate,
    RequirementDocumentUpsert,
    RequirementDocumentResponse,
    RequirementDocumentVersionInfo,
    RequirementDocumentStatus,
    SourceType,
    # Requirement Item schemas
    RequirementItemCreate,
    RequirementItemUpdate,
    RequirementItemUpsert,
    RequirementItemBatchUpsert,
    RequirementItemBatchUpsertResponse,
    RequirementItemResponse,
    RequirementItemStatusUpdate,
    RequirementItemStatus,
    RequirementItemPriority,
    # AI Suggestion schemas
    RequirementSuggestionRequest,
    RequirementSuggestion,
    RequirementSuggestionResponse,
)

__all__ = [
    # Common schemas
    "BaseResponse",
    "SuccessResponse",
    "ErrorResponse",
    "ValidationErrorResponse",
    "PaginationMeta",
    "PaginatedResponse",
    "ListResponse",
    "create_success_response",
    "create_error_response",
    "create_validation_error_response",
    "create_list_response",
    "create_paginated_response",
    # Project schemas
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectState",
    "SolutionOutlineBase",
    "SolutionOutlineCreate",
    "SolutionOutlineUpdate",
    "SolutionOutlineUpsert",
    "SolutionOutlineResponse",
    "SolutionOutlineVersionInfo",
    "SolutionOutlineStatus",
    "ADRBase",
    "ADRCreate",
    "ADRUpdate",
    "ADRResponse",
    "ReviewCommentBase",
    "ReviewCommentCreate",
    "ReviewCommentUpdate",
    "ReviewCommentResponse",
    "ReviewCommentStatus",
    "TeamBase",
    "TeamCreate",
    "TeamUpdate",
    "TeamResponse",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskStatus",
    "SSEMessageBase",
    "SSEMessageCreate",
    "SSEMessageResponse",
    "SSEClientInfo",
    "SSEClientsResponse",
    "SSEClientDisconnectResponse",
    "SSEClientsDisconnectResponse",
    "SSEHeartbeatResponse",
    "LLMRequestBase",
    "LLMRequest",
    "LLMStreamRequest",
    "LLMResponseBase",
    "LLMResponse",
    "LLMStreamResponse",
    "LLMErrorResponse",
    # Requirements schemas
    "RequirementBase",
    "RequirementCreate",
    "RequirementUpdate",
    "RequirementResponse",
    "RequirementCategory",
    "RequirementStatus",
    "RequirementDocumentBase",
    "RequirementDocumentCreate",
    "RequirementDocumentUpdate",
    "RequirementDocumentUpsert",
    "RequirementDocumentResponse",
    "RequirementDocumentVersionInfo",
    "RequirementDocumentStatus",
    "SourceType",
    # Requirement Item schemas
    "RequirementItemCreate",
    "RequirementItemUpdate",
    "RequirementItemUpsert",
    "RequirementItemBatchUpsert",
    "RequirementItemBatchUpsertResponse",
    "RequirementItemResponse",
    "RequirementItemStatusUpdate",
    "RequirementItemStatus",
    "RequirementItemPriority",
    # AI Suggestion schemas
    "RequirementSuggestionRequest",
    "RequirementSuggestion",
    "RequirementSuggestionResponse",
]